import { getExplorerLaunchParameters, hasRecentlyLoggedIn, isMobile } from './browser'
import { SKIP_SETUP } from './url'

/**
 * Try to launch the desktop version using the custom protocol `decentraland://position=x,y&realm=zzz`
 * and return a boolean that represents if a loss of focus was detected on the current window
 * (assuming it was due to the interaction generated by the desktop version)
 */
export const launchDesktopApp = async (force = false) => {
  if (isMobile() || SKIP_SETUP) {
    return false
  }

  if (hasRecentlyLoggedIn() && !force) {
    return false
  }

  const data = getExplorerLaunchParameters()
  let customProtocolParams: string[] = Object.entries(data).map(([key, value]) => `${key}=${value}`)

  const customProtocolTarget = `decentraland://?${customProtocolParams.join('&')}`

  // assume that the desktop version is installed only if
  // we detect a loss of focus on window
  let installed = false
  const isInstalled = () => {
    installed = true
  }
  window.addEventListener('blur', isInstalled)

  // inject an iframe that open the desktop version
  // NOTE: this can be also achieved with
  // ```js
  //   window.location.href = customProtocolTarget
  // ```
  // but in safari redirects into an invalid url if the desktop
  // client is not installed
  const iframe = document.createElement('iframe')
  iframe.setAttribute('style', 'display: none')
  iframe.src = customProtocolTarget
  document.body.appendChild(iframe)

  // wait half of a second to detect the loss of focus because
  // the time it takes for the `blur` event to be fired varies
  // depending on the browser
  return new Promise<boolean>((resolve) => {
    setTimeout(() => {
      window.removeEventListener('blur', isInstalled)
      document.body.removeChild(iframe)
      resolve(installed)
    }, 500)
  })
}
