on:
  pull_request:

name: Pull request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: npm

      - id: install
        name: install
        run: npm ci

      - name: build
        run: npm run build
      - name: test
        run: npm run test

      - name: deploy preview
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EXPLORER_WEB_BUCKET: ${{ secrets.EXPLORER_WEB_BUCKET }}
        if: ${{ steps.install.outputs.public_path }}
        run: |
          npx @dcl/cdn-uploader@next \
            --bucket $EXPLORER_WEB_BUCKET \
            --local-folder build \
            --bucket-folder "${{ steps.install.outputs.public_path }}"

      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Test this pull request

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            # Test this pull request
            This branch can be previewed at ${{ steps.install.outputs.public_url }}
          edit-mode: replace