on:
  pull_request:

name: Pull request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - id: install
        name: install
        run: npm ci

      - name: build
        run: npm run build
      - name: test
        run: npm run test

      - name: deploy preview
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EXPLORER_WEB_BUCKET: ${{ secrets.EXPLORER_WEB_BUCKET }}
        if: ${{ steps.install.outputs.public_path }}
        run: |
          npx @dcl/cdn-uploader@next \
            --bucket $EXPLORER_WEB_BUCKET \
            --local-folder build \
            --bucket-folder "${{ steps.install.outputs.public_path }}"

          npx @dcl/cdn-uploader@next \
            --bucket $EXPLORER_WEB_BUCKET \
            --local-folder node_modules/@dcl/unity-renderer \
            --bucket-folder "${{ steps.install.outputs.public_path }}/@/unity-renderer"

          npx @dcl/cdn-uploader@next \
            --bucket $EXPLORER_WEB_BUCKET \
            --local-folder node_modules/decentraland-kernel \
            --bucket-folder "${{ steps.install.outputs.public_path }}/@/kernel"

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        if: ${{ steps.install.outputs.public_url }}
        with:
          message: |
            This branch can be previewed at ${{ steps.install.outputs.public_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
